export const BRAND_COLORS = {
  primaryGreen: "#109448",
  darkGreen: "#006838",
  softGreen: "#92DDBF",
  pastelPeaGreen: "#ACD6A6",
  seafoamGreen: "#92DDBF",
  lightCyan: "#D3EDEE",
  successBg: "#F0FDF4",
  warningBg: "#FFF7ED",
  warningText: "#F1592B",
  warningBorder: "#F4845F",
  errorBg: "#FEF2F2",
  destructiveRed: "#BF1F2F",
  errorRed: "#EF4444",
  neutralText: "#22223B",
  neutralBorder: "#E5E7EB",
  mutedBg: "#F3F4F6",
  subtleBg: "#F9FAFB",
  white: "#FFFFFF",
  black: "#000000",
  grey: "#808080",
  ashWhite: "#ECECEC",
  gold: "#CBA135",
  brightGold: "#FFD026",
  paleGold: "#FFF48E",
} as const;

export const PDF_THEME_PALETTES = {
  orange: {
    default: "#F4845F",
    hover: "#F1592B",
    disabled: "#F7B267",
    foreground: "#FFFFFF",
    disabledForeground: "#000000",
  },
  green: {
    default: BRAND_COLORS.primaryGreen,
    hover: BRAND_COLORS.darkGreen,
    disabled: BRAND_COLORS.seafoamGreen,
    foreground: BRAND_COLORS.white,
    disabledForeground: BRAND_COLORS.black,
  },
  pink: {
    default: "#F686C3",
    hover: "#E13481",
    disabled: "#FFCEE9",
    foreground: BRAND_COLORS.white,
    disabledForeground: BRAND_COLORS.black,
  },
  blue: {
    default: "#40CFFF",
    hover: "#026BA9",
    disabled: "#CAF0F8",
    foreground: BRAND_COLORS.white,
    disabledForeground: BRAND_COLORS.black,
  },
  neutral: {
    default: BRAND_COLORS.neutralText,
    hover: BRAND_COLORS.black,
    disabled: "#F2E9E4",
    foreground: BRAND_COLORS.white,
    disabledForeground: BRAND_COLORS.black,
  },
  red: {
    default: BRAND_COLORS.errorRed,
    hover: BRAND_COLORS.destructiveRed,
    disabled: "#F9EBEB",
    foreground: BRAND_COLORS.white,
    disabledForeground: BRAND_COLORS.black,
  },
} as const;

export const SEMANTIC_SURFACE_COLORS = {
  light: {
    bg: BRAND_COLORS.white,
    subtle: BRAND_COLORS.subtleBg,
    muted: BRAND_COLORS.mutedBg,
    emphasized: BRAND_COLORS.neutralBorder,
    inverted: BRAND_COLORS.black,
    panel: BRAND_COLORS.white,
    error: BRAND_COLORS.errorBg,
    warning: BRAND_COLORS.warningBg,
    success: BRAND_COLORS.successBg,
    info: "#EFF6FF",
  },
  dark: {
    bg: BRAND_COLORS.black,
    subtle: "#030712",
    muted: "#111827",
    emphasized: "#1F2937",
    inverted: BRAND_COLORS.white,
    panel: "#030712",
    error: "#450A0A",
    warning: "#431407",
    success: "#052E16",
    info: "#172554",
  },
} as const;

export const STANDARD_COLOR_TOKENS = {
  brand: BRAND_COLORS,
  palettes: PDF_THEME_PALETTES,
  surfaces: SEMANTIC_SURFACE_COLORS,
} as const;
